### ISSUE TITLE
Not Working somehow, Please fix it, Thank you.

### ISSUE THREAD

**Issue by Johanna007** [v1shwa/gdget#2] opened 2020-05-14 04:00 UTC
Hi Please Make the script to resume files. By the way the downloading not succeeding to 100%, Somehow it is not downloading successfully, Please fix it.

**Comment by v1shwa** [comment] 2020-05-14 04:50
Could you please elaborate? I use it almost everyday & it works for me. Are you trying to download a folder? @johanna007

**Comment by v1shwa** [comment] 2021-03-28 10:52
Closing this as the issue is not clear.

**Closed as completed by v1shwa** 2021-03-28 10:52 UTC
